const OPENAI_COMPAT = { supportsDeveloperRole: false, maxTokensField: "max_tokens" } as const;

// Fireworks' OpenAI-compatible inference/v1 endpoint only works reliably for
// models that currently advertise Serverless support in the Fireworks model library.
// Keep this catalog curated to that set so users don't select models that 404 with
// "model not found, inaccessible, and/or not deployed".
// Whisper/audio transcription and image-generation models are intentionally excluded
// here because they use separate Fireworks APIs instead of the chat-completions path.
export const FIREWORKS_SERVERLESS_MODELS = [
	{
		id: "accounts/fireworks/models/glm-5",
		name: "GLM-5",
		reasoning: true,
		input: ["text"],
		cost: { input: 1.0, output: 3.2, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 202752,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/glm-4p7",
		name: "GLM-4.7",
		reasoning: true,
		input: ["text"],
		cost: { input: 0.6, output: 2.2, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 202752,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/kimi-k2-instruct-0905",
		name: "Kimi K2 Instruct 0905",
		reasoning: false,
		input: ["text"],
		cost: { input: 0.6, output: 2.5, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 262144,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/kimi-k2-thinking",
		name: "Kimi K2 Thinking",
		reasoning: true,
		input: ["text"],
		cost: { input: 0.6, output: 2.5, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 262144,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/kimi-k2p5",
		name: "Kimi K2.5",
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.6, output: 3.0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 262144,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/deepseek-v3p1",
		name: "DeepSeek V3.1",
		reasoning: true,
		input: ["text"],
		cost: { input: 0.56, output: 1.68, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 163840,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/deepseek-v3p2",
		name: "DeepSeek V3.2",
		reasoning: true,
		input: ["text"],
		cost: { input: 0.56, output: 1.68, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 163840,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/qwen3-8b",
		name: "Qwen3 8B",
		reasoning: false,
		input: ["text"],
		cost: { input: 0.2, output: 0.2, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 40960,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/qwen3-vl-235b-a22b-instruct",
		name: "Qwen3 VL 235B A22B Instruct",
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.22, output: 0.88, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 262144,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/qwen3-vl-30b-a3b-instruct",
		name: "Qwen3 VL 30B A3B Instruct",
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.15, output: 0.6, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 262144,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/qwen3-vl-30b-a3b-thinking",
		name: "Qwen3 VL 30B A3B Thinking",
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.15, output: 0.6, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 262144,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/minimax-m2p1",
		name: "MiniMax M2.1",
		reasoning: false,
		input: ["text"],
		cost: { input: 0.3, output: 1.2, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 204800,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/minimax-m2p5",
		name: "MiniMax M2.5",
		reasoning: false,
		input: ["text"],
		cost: { input: 0.3, output: 1.2, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 196608,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/gpt-oss-120b",
		name: "GPT-OSS 120B",
		reasoning: true,
		input: ["text"],
		cost: { input: 0.15, output: 0.6, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 131072,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
	{
		id: "accounts/fireworks/models/gpt-oss-20b",
		name: "GPT-OSS 20B",
		reasoning: true,
		input: ["text"],
		cost: { input: 0.07, output: 0.3, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 131072,
		maxTokens: 16384,
		compat: OPENAI_COMPAT,
	},
];

export const FIREWORKS_SERVERLESS_MODEL_IDS = new Set(FIREWORKS_SERVERLESS_MODELS.map((model) => model.id));
export const DEFAULT_FIREWORKS_MODEL_ID = FIREWORKS_SERVERLESS_MODELS[0]!.id;
